// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: econ_shared_enums.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Steam.Protos.Dota2 {

  /// <summary>Holder for reflection information generated from econ_shared_enums.proto</summary>
  public static partial class EconSharedEnumsReflection {

    #region Descriptor
    /// <summary>File descriptor for econ_shared_enums.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static EconSharedEnumsReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChdlY29uX3NoYXJlZF9lbnVtcy5wcm90byI+ChFDTXNnR2VuZXJpY1Jlc3Vs",
            "dBISCgdlcmVzdWx0GAEgASgNOgEyEhUKDWRlYnVnX21lc3NhZ2UYAiABKAkq",
            "LAoORUdDRWNvbkJhc2VNc2cSGgoVa19FTXNnR0NHZW5lcmljUmVzdWx0EJMU",
            "KpsCCg5FR0NNc2dSZXNwb25zZRIWChJrX0VHQ01zZ1Jlc3BvbnNlT0sQABIa",
            "ChZrX0VHQ01zZ1Jlc3BvbnNlRGVuaWVkEAESHwoba19FR0NNc2dSZXNwb25z",
            "ZVNlcnZlckVycm9yEAISGwoXa19FR0NNc2dSZXNwb25zZVRpbWVvdXQQAxIb",
            "ChdrX0VHQ01zZ1Jlc3BvbnNlSW52YWxpZBAEEhsKF2tfRUdDTXNnUmVzcG9u",
            "c2VOb01hdGNoEAUSIAoca19FR0NNc2dSZXNwb25zZVVua25vd25FcnJvchAG",
            "Eh8KG2tfRUdDTXNnUmVzcG9uc2VOb3RMb2dnZWRPbhAHEhoKFmtfRUdDTXNn",
            "RmFpbGVkVG9DcmVhdGUQCCrFBQoVRUdDTXNnVXNlSXRlbVJlc3BvbnNlEiQK",
            "IGtfRUdDTXNnVXNlSXRlbVJlc3BvbnNlX0l0ZW1Vc2VkEAASLgoqa19FR0NN",
            "c2dVc2VJdGVtUmVzcG9uc2VfR2lmdE5vT3RoZXJQbGF5ZXJzEAESJwoja19F",
            "R0NNc2dVc2VJdGVtUmVzcG9uc2VfU2VydmVyRXJyb3IQAhIyCi5rX0VHQ01z",
            "Z1VzZUl0ZW1SZXNwb25zZV9NaW5pR2FtZUFscmVhZHlTdGFydGVkEAMSMQot",
            "a19FR0NNc2dVc2VJdGVtUmVzcG9uc2VfSXRlbVVzZWRfSXRlbXNHcmFudGVk",
            "EAQSNwoza19FR0NNc2dVc2VJdGVtUmVzcG9uc2VfRHJvcFJhdGVCb251c0Fs",
            "cmVhZHlHcmFudGVkEAUSMAosa19FR0NNc2dVc2VJdGVtUmVzcG9uc2VfTm90",
            "SW5Mb3dQcmlvcml0eVBvb2wQBhIuCiprX0VHQ01zZ1VzZUl0ZW1SZXNwb25z",
            "ZV9Ob3RIaWdoRW5vdWdoTGV2ZWwQBxIqCiZrX0VHQ01zZ1VzZUl0ZW1SZXNw",
            "b25zZV9FdmVudE5vdEFjdGl2ZRAIEjcKM2tfRUdDTXNnVXNlSXRlbVJlc3Bv",
            "bnNlX0l0ZW1Vc2VkX0V2ZW50UG9pbnRzR3JhbnRlZBAJEi4KKmtfRUdDTXNn",
            "VXNlSXRlbVJlc3BvbnNlX01pc3NpbmdSZXF1aXJlbWVudBAKEjAKLGtfRUdD",
            "TXNnVXNlSXRlbVJlc3BvbnNlX0Vtb3RpY29uVW5sb2NrX05vTmV3EAsSMwov",
            "a19FR0NNc2dVc2VJdGVtUmVzcG9uc2VfRW1vdGljb25VbmxvY2tfQ29tcGxl",
            "dGUQDBIvCitrX0VHQ01zZ1VzZUl0ZW1SZXNwb25zZV9JdGVtVXNlZF9Db21w",
            "ZW5kaXVtEA1CFaoCElN0ZWFtLlByb3Rvcy5Eb3RhMg=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Steam.Protos.Dota2.EGCEconBaseMsg), typeof(global::Steam.Protos.Dota2.EGCMsgResponse), typeof(global::Steam.Protos.Dota2.EGCMsgUseItemResponse), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Steam.Protos.Dota2.CMsgGenericResult), global::Steam.Protos.Dota2.CMsgGenericResult.Parser, new[]{ "Eresult", "DebugMessage" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  public enum EGCEconBaseMsg {
    [pbr::OriginalName("k_EMsgGCGenericResult")] KEmsgGcgenericResult = 2579,
  }

  public enum EGCMsgResponse {
    [pbr::OriginalName("k_EGCMsgResponseOK")] KEgcmsgResponseOk = 0,
    [pbr::OriginalName("k_EGCMsgResponseDenied")] KEgcmsgResponseDenied = 1,
    [pbr::OriginalName("k_EGCMsgResponseServerError")] KEgcmsgResponseServerError = 2,
    [pbr::OriginalName("k_EGCMsgResponseTimeout")] KEgcmsgResponseTimeout = 3,
    [pbr::OriginalName("k_EGCMsgResponseInvalid")] KEgcmsgResponseInvalid = 4,
    [pbr::OriginalName("k_EGCMsgResponseNoMatch")] KEgcmsgResponseNoMatch = 5,
    [pbr::OriginalName("k_EGCMsgResponseUnknownError")] KEgcmsgResponseUnknownError = 6,
    [pbr::OriginalName("k_EGCMsgResponseNotLoggedOn")] KEgcmsgResponseNotLoggedOn = 7,
    [pbr::OriginalName("k_EGCMsgFailedToCreate")] KEgcmsgFailedToCreate = 8,
  }

  public enum EGCMsgUseItemResponse {
    [pbr::OriginalName("k_EGCMsgUseItemResponse_ItemUsed")] KEgcmsgUseItemResponseItemUsed = 0,
    [pbr::OriginalName("k_EGCMsgUseItemResponse_GiftNoOtherPlayers")] KEgcmsgUseItemResponseGiftNoOtherPlayers = 1,
    [pbr::OriginalName("k_EGCMsgUseItemResponse_ServerError")] KEgcmsgUseItemResponseServerError = 2,
    [pbr::OriginalName("k_EGCMsgUseItemResponse_MiniGameAlreadyStarted")] KEgcmsgUseItemResponseMiniGameAlreadyStarted = 3,
    [pbr::OriginalName("k_EGCMsgUseItemResponse_ItemUsed_ItemsGranted")] KEgcmsgUseItemResponseItemUsedItemsGranted = 4,
    [pbr::OriginalName("k_EGCMsgUseItemResponse_DropRateBonusAlreadyGranted")] KEgcmsgUseItemResponseDropRateBonusAlreadyGranted = 5,
    [pbr::OriginalName("k_EGCMsgUseItemResponse_NotInLowPriorityPool")] KEgcmsgUseItemResponseNotInLowPriorityPool = 6,
    [pbr::OriginalName("k_EGCMsgUseItemResponse_NotHighEnoughLevel")] KEgcmsgUseItemResponseNotHighEnoughLevel = 7,
    [pbr::OriginalName("k_EGCMsgUseItemResponse_EventNotActive")] KEgcmsgUseItemResponseEventNotActive = 8,
    [pbr::OriginalName("k_EGCMsgUseItemResponse_ItemUsed_EventPointsGranted")] KEgcmsgUseItemResponseItemUsedEventPointsGranted = 9,
    [pbr::OriginalName("k_EGCMsgUseItemResponse_MissingRequirement")] KEgcmsgUseItemResponseMissingRequirement = 10,
    [pbr::OriginalName("k_EGCMsgUseItemResponse_EmoticonUnlock_NoNew")] KEgcmsgUseItemResponseEmoticonUnlockNoNew = 11,
    [pbr::OriginalName("k_EGCMsgUseItemResponse_EmoticonUnlock_Complete")] KEgcmsgUseItemResponseEmoticonUnlockComplete = 12,
    [pbr::OriginalName("k_EGCMsgUseItemResponse_ItemUsed_Compendium")] KEgcmsgUseItemResponseItemUsedCompendium = 13,
  }

  #endregion

  #region Messages
  public sealed partial class CMsgGenericResult : pb::IMessage<CMsgGenericResult>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<CMsgGenericResult> _parser = new pb::MessageParser<CMsgGenericResult>(() => new CMsgGenericResult());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<CMsgGenericResult> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Steam.Protos.Dota2.EconSharedEnumsReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CMsgGenericResult() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CMsgGenericResult(CMsgGenericResult other) : this() {
      _hasBits0 = other._hasBits0;
      eresult_ = other.eresult_;
      debugMessage_ = other.debugMessage_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CMsgGenericResult Clone() {
      return new CMsgGenericResult(this);
    }

    /// <summary>Field number for the "eresult" field.</summary>
    public const int EresultFieldNumber = 1;
    private readonly static uint EresultDefaultValue = 2;

    private uint eresult_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint Eresult {
      get { if ((_hasBits0 & 1) != 0) { return eresult_; } else { return EresultDefaultValue; } }
      set {
        _hasBits0 |= 1;
        eresult_ = value;
      }
    }
    /// <summary>Gets whether the "eresult" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool HasEresult {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "eresult" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearEresult() {
      _hasBits0 &= ~1;
    }

    /// <summary>Field number for the "debug_message" field.</summary>
    public const int DebugMessageFieldNumber = 2;
    private readonly static string DebugMessageDefaultValue = "";

    private string debugMessage_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string DebugMessage {
      get { return debugMessage_ ?? DebugMessageDefaultValue; }
      set {
        debugMessage_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "debug_message" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool HasDebugMessage {
      get { return debugMessage_ != null; }
    }
    /// <summary>Clears the value of the "debug_message" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearDebugMessage() {
      debugMessage_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as CMsgGenericResult);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(CMsgGenericResult other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Eresult != other.Eresult) return false;
      if (DebugMessage != other.DebugMessage) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (HasEresult) hash ^= Eresult.GetHashCode();
      if (HasDebugMessage) hash ^= DebugMessage.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (HasEresult) {
        output.WriteRawTag(8);
        output.WriteUInt32(Eresult);
      }
      if (HasDebugMessage) {
        output.WriteRawTag(18);
        output.WriteString(DebugMessage);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (HasEresult) {
        output.WriteRawTag(8);
        output.WriteUInt32(Eresult);
      }
      if (HasDebugMessage) {
        output.WriteRawTag(18);
        output.WriteString(DebugMessage);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (HasEresult) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Eresult);
      }
      if (HasDebugMessage) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(DebugMessage);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(CMsgGenericResult other) {
      if (other == null) {
        return;
      }
      if (other.HasEresult) {
        Eresult = other.Eresult;
      }
      if (other.HasDebugMessage) {
        DebugMessage = other.DebugMessage;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Eresult = input.ReadUInt32();
            break;
          }
          case 18: {
            DebugMessage = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Eresult = input.ReadUInt32();
            break;
          }
          case 18: {
            DebugMessage = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
