<Project>
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <BuildDir>$(MSBuildThisFileDirectory)build/</BuildDir>
    <SourceDir>$(MSBuildThisFileDirectory)src/</SourceDir>
    <ProjectBuildDir>$(BuildDir)$(MSBuildProjectName)/</ProjectBuildDir>
    <BaseOutputPath>$(ProjectBuildDir)bin/</BaseOutputPath>
    <BaseIntermediateOutputPath>$(ProjectBuildDir)obj/</BaseIntermediateOutputPath>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
  </PropertyGroup>
</Project>
